name: publish

on: [push]

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build Docker image
      run: |
        docker build . --tag ghcr.io/delxhq/node-gyp-images:latest
        docker push ghcr.io/delxhq/node-gyp-images:latest
